import * as THREE from 'three';
import {PointerLockControls} from 'three/addons/controls/PointerLockControls.js';

const $=s=>document.querySelector(s), clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
let scene,camera,renderer,controls,clock;
const keys={}, solids=[], interactives=[], echoes=[], notes=[];
let started=false, paused=false, loop=0, time=599, last=0, flashlight=true, crouch=false, sprint=false;
let objective='Explore Central Control. Find out why the recovery protocol is active.';
let instability=0, playerSpeed=3.25, scannerMode='NORMAL', fuse=false, archiveFound=false, badge=false, coreUnlocked=false, endingShown=false;
let witness, witnessState='IDLE', witnessTarget=new THREE.Vector3(), witnessMemory={}, lastPlayerPos=new THREE.Vector3(), noise=0;
const saveKey='tl10-save-v1';

function mat(c,rough=0.8,metal=0){return new THREE.MeshStandardMaterial({color:c,roughness:rough,metalness:metal});}
const M={wall:mat(0x252c2d),floor:mat(0x161b1c),metal:mat(0x4a5556,.45,.8),dark:mat(0x080b0c),white:mat(0xb9c0bd,.55),yellow:mat(0xb09a50,.6,.25),red:mat(0x7b2525,.55,.25),glass:new THREE.MeshPhysicalMaterial({color:0x557077,roughness:.12,metalness:.15,transparent:true,opacity:.28}),green:mat(0x4c927f,.45,.2)};
function box(name,x,y,z,sx,sy,sz,material=M.wall,solid=true){let m=new THREE.Mesh(new THREE.BoxGeometry(sx,sy,sz),material);m.name=name;m.position.set(x,y,z);scene.add(m);if(solid)solids.push({mesh:m,box:new THREE.Box3().setFromObject(m)});return m}
function label(text,x,y,z,size=.12,color=0xc9d4d4){let c=document.createElement('canvas'),ctx=c.getContext('2d');c.width=512;c.height=128;ctx.fillStyle='#000';ctx.fillRect(0,0,512,128);ctx.fillStyle='#'+color.toString(16).padStart(6,'0');ctx.font='bold 34px monospace';ctx.textAlign='center';ctx.fillText(text,256,76);let t=new THREE.CanvasTexture(c);let s=new THREE.Sprite(new THREE.SpriteMaterial({map:t,transparent:true}));s.position.set(x,y,z);s.scale.set(size*4,size,1);scene.add(s);return s}
function light(x,y,z,c=0xbfd7dd,intensity=2,dist=9){let p=new THREE.PointLight(c,intensity,dist);p.position.set(x,y,z);scene.add(p);return p}
function tube(x,y,z,rot=0){let o=box('fluorescent',x,y,z,.14,.08,3,M.white,false);o.rotation.y=rot;light(x,y-.1,z,0xcfe6ff,1.8,8)}
function interact(name,pos,range,fn,text){let o=new THREE.Object3D();o.position.copy(pos);o.userData={name,range,fn,text,enabled:true};scene.add(o);interactives.push(o);return o}
function makeRoom(x,z,w,d,name){box(name+' floor',x,0,z,w,.2,d,M.floor);box(name+' ceiling',x,4,z,w,.2,d,M.dark);box(name+' north',x,2,z-d/2,w,4,.2,M.wall);box(name+' south',x,2,z+d/2,w,4,.2,M.wall);box(name+' west',x-w/2,2,z,.2,4,d,M.wall);box(name+' east',x+w/2,2,z,.2,4,d,M.wall);label(name.toUpperCase(),x,3.65,z-d/2+.12,.09)}
function door(name,x,z,axis='x',locked=false){let o=box(name,x,2,z,axis==='x'?1.7:.2,4,axis==='x'?.2:1.7,M.metal,true);o.userData={door:true,locked,open:false,name};interact(name,new THREE.Vector3(x,1.5,z),3,()=>toggleDoor(o),locked?'LOCKED — FIND A WAY AROUND':'OPEN / CLOSE');return o}
function toggleDoor(o){if(o.userData.locked){msg('ACCESS DENIED. The facility remembers this door.');noise+=.15;return}o.visible=!o.visible;o.userData.open=!o.userData.open;noise+=.1;}
function buildFacility(){
 makeRoom(0,0,14,12,'CENTRAL CONTROL');
 makeRoom(16,0,14,12,'SECURITY');makeRoom(0,-16,14,12,'MAINTENANCE');makeRoom(16,-16,14,12,'RESEARCH');makeRoom(32,-16,14,12,'ARCHIVE');makeRoom(32,-32,18,14,'OBSERVATION CORE');
 // corridors / connectors
 box('corridor A',8,0,3,2,.2,6,M.floor);box('corridor A wall',8,2,0,2,4,.2,M.wall);box('corridor B',0,-6,3,2,.2,6,M.floor);box('corridor C',8,-16,3,2,.2,6,M.floor);box('corridor D',16,-8,3,2,.2,6,M.floor);box('corridor E',24,-16,3,2,.2,6,M.floor);box('corridor F',32,-24,3,2,.2,6,M.floor);
 // walls for connectors
 box('A1',7,2,0, .2,4,12,M.wall);box('A2',9,2,0,.2,4,12,M.wall);box('B1',-7,2,-6,.2,4,12,M.wall);box('B2',7,2,-6,.2,4,12,M.wall);box('C1',7,2,-16,.2,4,12,M.wall);box('C2',9,2,-16,.2,4,12,M.wall);box('D1',15,2,-8,.2,4,6,M.wall);box('D2',17,2,-8,.2,4,6,M.wall);box('E1',23,2,-16,.2,4,12,M.wall);box('E2',25,2,-16,.2,4,12,M.wall);box('F1',31,2,-24,.2,4,8,M.wall);box('F2',33,2,-24,.2,4,8,M.wall);
 // doors at connectors
 door('SECURITY ACCESS',7.95,0,'x',false);door('MAINTENANCE ACCESS',0,-6,'z',false);door('RESEARCH ACCESS',8,-15.95,'x',false);door('ARCHIVE ACCESS',24,-16,'x',false);door('CORE BULKHEAD',32,-24,'z',true);
 // details
 for(let z=-4;z<5;z+=3){tube(-3.5,3.65,z);tube(3.5,3.65,z)}
 for(let z=-4;z<5;z+=3){tube(12.5,3.65,z);tube(19.5,3.65,z)}
 for(let x=28;x<=36;x+=4){tube(x,3.65,-19);tube(x,3.65,-13)}
 for(let x=28;x<=36;x+=4){tube(x,3.65,-28);}
 // consoles
 box('control desk',0,1,-2,7,1,1.2,M.metal);box('monitor',-2.5,2,-2,.12,1.2,2,M.dark);box('monitor',0,2,-2,.12,1.2,2,M.dark);box('monitor',2.5,2,-2,.12,1.2,2,M.dark);
 interact('SECURITY TERMINAL',new THREE.Vector3(0,2,-2),3,()=>openCCTV(),'ACCESS CCTV');
 interact('RECOVERY CONSOLE',new THREE.Vector3(3,1.6,-2),3,()=>recoveryConsole(),'CHECK PROTOCOL');
 interact('RADIO',new THREE.Vector3(-3,1.5,-2),3,()=>radioEvent(),'LISTEN');
 // key items
 let f=box('FUSE',-3,1.2,-18,.3,.25,.3,M.yellow,false);interact('FUSE',new THREE.Vector3(-3,1.2,-18),2,()=>{if(!fuse){fuse=true;f.visible=false;note('Recovered a ceramic fuse from Maintenance.');msg('FUSE ACQUIRED. The generator should accept it.');objective='Install the fuse in Central Control.'}},'TAKE FUSE');
 interact('GENERATOR',-1?new THREE.Vector3(-4,1,-3):new THREE.Vector3(-4,1,-3),3,()=>{if(fuse){coreUnlocked=true;objective='Reach Research. Find the scientist badge.';note('The generator accepted the fuse. A deeper section is powered.');msg('POWER RESTORED. Somewhere below, a lock released.');}else msg('The generator is missing a fuse.');},'SERVICE GENERATOR');
 // research badge
 let b=box('BADGE',12,1,-17,.4,.08,.25,M.yellow,false);interact('SCIENTIST BADGE',new THREE.Vector3(12,1,-17),2,()=>{if(!badge){badge=true;b.visible=false;note('Dr. Mara Venn — Lead Researcher. Clearance: OBSERVATION CORE.');objective='Use the badge to enter the Archive and find your original experiment record.';msg('BADGE ACQUIRED.');}},'TAKE BADGE');
 // archive record
 let file=box('FILE',31,1,-17,.5,.05,.35,M.white,false);interact('EMPLOYEE FILE',new THREE.Vector3(31,1,-17),2,()=>{if(badge&&!archiveFound){archiveFound=true;file.visible=false;instability+=18;note('My file contains my photograph, employment history, and a death certificate dated TOMORROW.');objective='Return to Central Control. The radio knows your voice.';msg('DEATH CERTIFICATE: TOMORROW.\n\nThe handwriting beneath it is yours.');}else if(!badge)msg('A locked archive drawer. Clearance required.');},'READ FILE');
 // core machine
 for(let r=3;r<=7;r+=1.2){let ring=new THREE.Mesh(new THREE.TorusGeometry(r,.12,12,96),new THREE.MeshStandardMaterial({color:0x668086,metalness:.8,roughness:.25,emissive:0x183337}));ring.rotation.x=Math.PI/2;ring.position.set(32,3,-32);scene.add(ring);}
 for(let i=0;i<12;i++){let a=i*Math.PI/6;let p=box('core strut',32+Math.cos(a)*6,2.4,-32+Math.sin(a)*6,.15,4,.15,M.metal);p.rotation.z=-Math.cos(a)*.5;p.rotation.x=Math.sin(a)*.5}
 light(32,3,-32,0x6ec6d0,7,18);
 interact('CORE CONTROL',new THREE.Vector3(32,1.4,-27),4,()=>coreChoice(),'OPERATE CORE');
 // impossible elevator
 interact('ELEVATOR',new THREE.Vector3(4,1,-4.5),3,()=>elevator(),'CALL ELEVATOR');
 // scanner
 interact('SCANNER CASE',new THREE.Vector3(5,1,-2),2,()=>{scannerMode=scannerMode==='NORMAL'?'TEMPORAL':'NORMAL';msg('SCANNER MODE: '+scannerMode);},'TOGGLE SCANNER');
}
function buildProps(){
 for(let i=0;i<18;i++){let x=-5+(i%6)*2,z=7-(i%3)*1.7;box('pipe',x,2.8,z,.18, .18,2.8,M.metal,false)}
 for(let i=0;i<30;i++){let x=27+(i%6)*1.1,z=-20-Math.floor(i/6)*1.3;box('archive shelf',x,2,z,.7,4,.2,M.metal)}
 for(let i=0;i<10;i++){let x=-5+(i%5)*2,z=-13;box('machine',x,1,z,1.2,2,1,M.metal);light(x,2.1,z,0x9db8b7,.4,4)}
}
function buildWitness(){let g=new THREE.Group();let body=new THREE.Mesh(new THREE.CapsuleGeometry(.45,2.7,8,12),mat(0x111415,.9));body.position.y=1.8;g.add(body);let head=new THREE.Mesh(new THREE.SphereGeometry(.55,12,8),mat(0x090b0c,.8));head.scale.set(.65,1.25,.7);head.position.y=3.5;g.add(head);let armMat=mat(0x0b0e0f,.9);for(let s of [-1,1]){let a=new THREE.Mesh(new THREE.CapsuleGeometry(.16,2.2,6,8),armMat);a.position.set(s*.62,1.9,0);a.rotation.z=s*.12;g.add(a)}g.position.set(4,0,-5);scene.add(g);witness=g}
function setup(){scene=new THREE.Scene();scene.background=new THREE.Color(0x030506);scene.fog=new THREE.FogExp2(0x06090a,.025);camera=new THREE.PerspectiveCamera(75,innerWidth/innerHeight,.05,150);camera.position.set(0,1.65,4);renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;document.body.prepend(renderer.domElement);controls=new PointerLockControls(camera,document.body);clock=new THREE.Clock();
 scene.add(new THREE.HemisphereLight(0x9db0b3,0x060708,.28));let amb=new THREE.AmbientLight(0x819295,.18);scene.add(amb);buildFacility();buildProps();buildWitness();
 let fl=new THREE.SpotLight(0xe5f4ff,8,25,Math.PI/7,.55,1.2);fl.position.set(0,0,0);fl.castShadow=true;scene.add(fl);camera.add(fl);fl.target.position.set(0,0,-10);camera.add(fl.target);camera.userData.flash=fl;
 window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});window.addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='KeyF')toggleFlash();if(e.code==='Tab'){e.preventDefault();toggleBook()}if(e.code==='KeyE')tryInteract();if(e.code==='KeyQ')keys.KeyQ=true;if(e.code==='KeyE')keys.KeyE=true});window.addEventListener('keyup',e=>keys[e.code]=false);renderer.domElement.addEventListener('click',()=>{if(started&&!paused)controls.lock()});controls.addEventListener('lock',()=>paused=false);controls.addEventListener('unlock',()=>{if(started)paused=true});load();requestAnimationFrame(tick)}
function toggleFlash(){flashlight=!flashlight;camera.userData.flash.intensity=flashlight?8:0;$('#flash').textContent='FLASHLIGHT '+(flashlight?'ON':'OFF')}
function updateMovement(dt){let dir=new THREE.Vector3();if(keys.KeyW)dir.z-=1;if(keys.KeyS)dir.z+=1;if(keys.KeyA)dir.x-=1;if(keys.KeyD)dir.x+=1;if(dir.lengthSq()){dir.normalize();let speed=keys.ShiftLeft||keys.ShiftRight?5.4:3.25;if(keys.ControlLeft||keys.ControlRight)speed=1.55;controls.moveRight(dir.x*speed*dt);controls.moveForward(-dir.z*speed*dt);noise+=dt*(speed>5?1.2:.35)}camera.position.y+=(keys.ControlLeft||keys.ControlRight?1.05:1.65-camera.position.y)*Math.min(1,dt*10);collide();}
function collide(){let p=new THREE.Vector3(camera.position.x,1,camera.position.z);for(let s of solids){let b=s.box.clone();b.min.y=-1;b.max.y=3.8;if(b.containsPoint(p)){let dx=Math.min(Math.abs(p.x-b.min.x),Math.abs(p.x-b.max.x)),dz=Math.min(Math.abs(p.z-b.min.z),Math.abs(p.z-b.max.z));if(dx<dz)camera.position.x=lastPlayerPos.x;else camera.position.z=lastPlayerPos.z;}}lastPlayerPos.copy(camera.position)}
function tryInteract(){if(!started||paused)return;let best=null,bd=999;for(let o of interactives){if(!o.userData.enabled)continue;let d=o.position.distanceTo(camera.position);if(d<o.userData.range&&d<bd){best=o;bd=d}}if(best)best.userData.fn();}
function nearestInteract(){let best=null,bd=999;for(let o of interactives){let d=o.position.distanceTo(camera.position);if(o.userData.enabled&&d<o.userData.range&&d<bd){best=o;bd=d}}$('#prompt').textContent=best?'[E] '+best.userData.text:''}
function loopReset(reason='RESET'){loop++;time=599;instability=clamp(instability+1,0,100);noise=0;camera.position.set(0,1.65,4);witness.position.set(4,0,-5);witnessState='IDLE';if(loop>=2&&!fuse){/* keep the world fair: fuse remains discoverable */}if(loop===2)objective='Find the Maintenance Sector. Something has changed.';if(loop===3)objective='Reach Security and inspect the CCTV terminal.';if(loop===4)objective='The facility is learning your habits. Find the scientist badge.';note('Cycle '+loop+' begins. Reason: '+reason+'.');msg('RECOVERY COMPLETE. CYCLE '+loop+'\nTHE FACILITY REMEMBERS.',2.5);save()}
function updateTime(dt){time-=dt;if(time<=0){loopReset('temporal collapse');return}let m=Math.floor(time/60),s=Math.floor(time%60);$('#timer').textContent=String(m).padStart(2,'0')+':'+String(s).padStart(2,'0');if(time<60){$('#timer').classList.add('low');instability=Math.min(100,instability+dt*.7)}else $('#timer').classList.remove('low')}
function updateWitness(dt){if(!witness)return;let dist=witness.position.distanceTo(camera.position);let dx=camera.position.x-witness.position.x,dz=camera.position.z-witness.position.z;let forward=new THREE.Vector3();camera.getWorldDirection(forward);let to=new THREE.Vector3(dx,0,dz).normalize();let seen=dist<18&&forward.dot(to)>.88&&!isOccluded(witness.position,camera.position);if(seen){witnessState='OBSERVE';witness.lookAt(camera.position.x,2,witness.position.z);instability+=dt*.65}else if(dist<11){witnessState='STALK';witnessTarget.copy(camera.position)}else if(noise>.35){witnessState='INVESTIGATE';witnessTarget.copy(camera.position);noise*=.96}else witnessState='IDLE';
 let speed=witnessState==='OBSERVE'?.25:witnessState==='STALK'?1.7:witnessState==='INVESTIGATE'?2.5:.35;if(witnessState!=='OBSERVE')moveWitness(witnessTarget,speed*dt);if(dist<1.25&&witnessState!=='OBSERVE'){instability=clamp(instability+25,0,100);loopReset('the Witness found you')}
 witness.rotation.y=Math.atan2(camera.position.x-witness.position.x,camera.position.z-witness.position.z);witness.visible=(loop>2||instability>35||dist<10);if(time<70&&loop>3)witness.visible=true}
function isOccluded(a,b){let ray=new THREE.Raycaster();let d=a.distanceTo(b);ray.set(b,new THREE.Vector3().subVectors(a,b).normalize());let hits=ray.intersectObjects(scene.children,true);return hits.some(h=>h.distance<d-.5&&h.object!==witness)}
function moveWitness(target,amt){let v=new THREE.Vector3(target.x-witness.position.x,0,target.z-witness.position.z);if(v.length()>0.2){v.normalize();witness.position.addScaledVector(v,amt)}}
function anomalyTick(dt){let phase=time<420?1:time<180?2:3;let rate=(instability/100)*.25+(phase===3?.08:0);if(Math.random()<rate*dt){instability=Math.min(100,instability+2);const events=[()=>flicker(),()=>echoEvent(),()=>architecturalEvent(),()=>audioAnomaly()];events[Math.floor(Math.random()*events.length)]()}}
function flicker(){let lights=scene.children.filter(x=>x.isPointLight);lights.forEach(l=>l.intensity*=.1);setTimeout(()=>lights.forEach(l=>l.intensity*=10),120+Math.random()*250);}
function echoEvent(){let e=new THREE.Mesh(new THREE.CapsuleGeometry(.35,2,6,8),new THREE.MeshBasicMaterial({color:0x8ba7a7,transparent:true,opacity:.18}));e.position.copy(camera.position);e.position.y=0;scene.add(e);echoes.push({mesh:e,life:5});note('Temporal echo observed at '+Math.ceil(10-time%10)+' seconds into the cycle.');}
function architecturalEvent(){let candidates=solids.filter(s=>s.mesh.name.includes('pipe')||s.mesh.name.includes('machine'));if(candidates.length){let s=candidates[Math.floor(Math.random()*candidates.length)];s.mesh.rotation.y+=Math.PI/2;setTimeout(()=>s.mesh.rotation.y-=Math.PI/2,1500)}}
function audioAnomaly(){msg('...footsteps behind you...',1.4);instability+=3}
function updateEchoes(dt){for(let i=echoes.length-1;i>=0;i--){echoes[i].life-=dt;echoes[i].mesh.material.opacity=Math.max(0,echoes[i].life/5*.18);if(echoes[i].life<=0){scene.remove(echoes[i].mesh);echoes.splice(i,1)}}}
function msg(t,d=2.4){let el=$('#message');el.textContent=t;el.classList.add('show');clearTimeout(msg.t);msg.t=setTimeout(()=>el.classList.remove('show'),d*1000)}
function note(t){notes.unshift(t);notes.splice(18);renderBook();}
function radioEvent(){if(loop<2){msg('RADIO: "Can you hear me?"');note('Radio transmission: an unknown voice asked whether I could hear it.')}else if(!archiveFound){msg('RADIO: "You always check the left corridor first."');instability+=7;note('The radio predicted my route.')}else{msg('RADIO — MY VOICE: "Do not enter the Core. I know what you become."');instability+=12;objective='The Core is calling. Reach it.'}}
function recoveryConsole(){if(!fuse)msg('TEMPORAL RECOVERY PROTOCOL — POWER FAULT');else if(!badge)msg('RECOVERY: STABLE. RESEARCH CLEARANCE REQUIRED.');else{objective='Reach the Observation Core. The bulkhead should now respond.';coreUnlocked=true;for(let o of interactives)if(o.userData.name==='CORE BULKHEAD'){o.userData.enabled=true;o.userData.locked=false}msg('CLEARANCE ACCEPTED. OBSERVATION CORE UNSEALED.');note('My credentials were accepted as LEAD RESEARCHER.')}save()}
function elevator(){instability+=8;msg('ELEVATOR B1... B2... B3... B4... B5... B6... B7... B8... B9... B10...');setTimeout(()=>{msg('THE FACILITY HAS NINE LEVELS.',2.5);camera.position.set(0,1.65,-8);note('The elevator reached a level that does not exist. A domestic corridor appeared, then vanished.');},1700)}
function openCCTV(){let old=paused;paused=true;let overlay=document.createElement('div');overlay.id='cctv';overlay.innerHTML='<div><h1>SECURITY NETWORK</h1><p>CAM 01 · CENTRAL CONTROL</p><pre id="cam">[ LIVE ]</pre><p>W/S switch camera · ESC close</p></div>';Object.assign(overlay.style,{position:'fixed',inset:0,zIndex:30,background:'#020606',color:'#9db6b6',font:'14px monospace',padding:'8vh 10vw'});document.body.appendChild(overlay);let cam=0;let iv=setInterval(()=>{cam++;let behind=cam>3?'\n\nA FIGURE IS STANDING BEHIND YOU.':'';overlay.querySelector('#cam').textContent='CAM '+String((cam%9)+1).padStart(2,'0')+'\n\n'+(cam%2?'[ NO SIGNAL ]':'[ LIVE ]\nTIME: '+String(Math.floor(time)).padStart(4,'0'))+behind;if(cam===5){instability+=10;note('CCTV displayed a future version of me.')}} ,1100);let close=()=>{clearInterval(iv);overlay.remove();paused=old;window.removeEventListener('keydown',close)};window.addEventListener('keydown',e=>{if(e.code==='Escape')close()})}
function coreChoice(){if(!coreUnlocked){msg('CORE BULKHEAD: ACCESS DENIED.');return}if(endingShown)return;$('#ending').style.display='flex';$('#endingInner').innerHTML='<div class="endCard"><h1>THE LAST TEN MINUTES</h1><p>The rings are turning. Every reconstruction of you is still here.</p><p>You know the truth now: the Witness was the first copy. It remembers every failure.</p><div class="choice"><button data-end="escape">RELEASE</button><button data-end="destroy">DESTROY</button><button data-end="merge">MERGE</button><button data-end="reset">RESET</button></div></div>';document.querySelectorAll('.choice button').forEach(b=>b.onclick=()=>ending(b.dataset.end));endingShown=true}
function ending(type){let texts={escape:['RELEASE','You open the containment gate. The Witness walks past you into the cold mountain air.\n\nOutside, dawn is waiting. In the reflection of the glass door, another you is still inside.'],destroy:['DESTROY','You overload the reconstruction engine. The Witness disappears. So does every memory of the person you were.\n\nThe facility becomes silent. You remain.'],merge:['MERGE','You step into the ring. Your memories spread through every corridor.\n\nThe opening scene plays again. This time, you are standing in the background.'],reset:['RESET','You press RESET.\n\n10:00.\n\nThe monitor reads: TEMPORAL RECOVERY PROTOCOL ACTIVE.\n\nA voice whispers: "Thank you for teaching me."']}[type];$('#endingInner').innerHTML='<div class="endCard"><h1>'+texts[0]+'</h1><p>'+texts[1].replace(/\n\n/g,'<br><br>')+'</p><p>Cycle '+loop+' · Instability '+Math.round(instability)+'%</p><button onclick="location.reload()">REPLAY</button></div>';localStorage.setItem(saveKey,JSON.stringify({completed:true,ending:type,loop}))}
function toggleBook(){let b=$('#notebook');let open=b.style.display==='flex';b.style.display=open?'none':'flex';if(!open){paused=true;renderBook()}else paused=false}
function renderBook(){let c=$('#bookContent');if(!c)return;let tab=document.querySelector('.tabs .active')?.dataset.tab||'objectives';let arr={objectives:[objective],clues:notes.slice(0,8),timeline:['02:30 — consciousness restored.','09:59 — recovery countdown begins.','Cycle '+loop+' — current reconstruction.'],anomalies:notes.filter(n=>/echo|CCTV|radio|death|facility|elevator/i.test(n))}[tab];c.innerHTML=arr.map((x,i)=>'<div class="entry"><b>'+String(i+1).padStart(2,'0')+'</b> — '+x+'</div>').join('')}
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderBook()});$('#closeBook').onclick=()=>toggleBook();
function save(){localStorage.setItem(saveKey,JSON.stringify({loop,time,instability,fuse,archiveFound,badge,coreUnlocked,notes}))}
function load(){try{let s=JSON.parse(localStorage.getItem(saveKey));if(s&&!s.completed){loop=s.loop||0;instability=s.instability||0;fuse=!!s.fuse;archiveFound=!!s.archiveFound;badge=!!s.badge;coreUnlocked=!!s.coreUnlocked;notes=s.notes||[];if(fuse){let f=scene.getObjectByName('FUSE');if(f)f.visible=false}objective=loop>2?'The facility knows your routines. Find the truth.':objective;}}catch(e){console.warn(e)}}
function tick(t){requestAnimationFrame(tick);let dt=Math.min(.05,(t-last)/1000||0);last=t;if(started&&!paused){updateMovement(dt);updateTime(dt);updateWitness(dt);anomalyTick(dt);updateEchoes(dt);nearestInteract();}renderer.render(scene,camera)}
$('#start').onclick=()=>{if(!started){started=true;$('#boot').style.opacity='0';setTimeout(()=>$('#boot').style.display='none',800);controls.lock();note('I woke on the floor at 02:30. The recovery protocol says the cycle lasts ten minutes.');}else controls.lock()};
setup();
